
ros__parameters:
  update_rate: 30  # Hz
  # -- 控制器配置 --
  # 将所有控制器的定义都放在 controller_manager.ros__parameters 下面
  # 1. Joint State Broadcaster 的配置
  joint_state_broadcaster:
    type: joint_state_broadcaster/JointStateBroadcaster
  # 2. Gripper Action Controller 的完整配置
  misumi_gripper_controller:
    type: gripper_controllers/GripperActionController
    # --- 所有特定于该控制器的参数都应该在这里 ---
    joint: gripper_joint      # 确保这个名字与 URDF 中的关节名完全匹配
    goal_tolerance: 0.001     # meters (1mm)
    # 其他 gripper_controllers/GripperActionController 可能需要的参数...