controller_manager:
  ros__parameters:
    update_rate: 30 # Hz

# Parameters for the GripperActionController
misumi_gripper_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints: 
      - gripper_joint # Must match the joint name in the URDF
    interface_name: position
    
    # These are the positions for "open" and "closed" states
    # GripperCommand action defines "position" from 0.0 (closed) to 1.0 (open)
    # The controller maps these to the real joint limits.
    # It is recommended to use the joint limits from the URDF instead.
    # The controller will read them automatically if they are defined.
    # We will define them in the URDF.

gripper_joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    # 这个参数现在会被正确地应用到这个控制器实例上
    joint_states_topic_name: /eyou_robot/joint_states