controller_manager:
  ros__parameters:
    update_rate: 30 # Hz

    # The list of controllers to be loaded and started
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    misumi_gripper_controller:
      type: position_controllers/GripperActionController

# Parameters for the GripperActionController
misumi_gripper_controller:
  ros__parameters:
    joint: gripper_joint # Must match the joint name in the URDF
    goal_tolerance: 0.001 # meters (1mm)
    
    # These are the positions for "open" and "closed" states
    # GripperCommand action defines "position" from 0.0 (closed) to 1.0 (open)
    # The controller maps these to the real joint limits.
    # It is recommended to use the joint limits from the URDF instead.
    # The controller will read them automatically if they are defined.
    # We will define them in the URDF.